version: '3.8'

services:
  db-postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  api-node-rest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-apirest-app
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db-postgres
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      PORT: ${PORT}
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
    depends_on:
      - db-postgres

volumes:
  db_data: