# Usa la imagen oficial de PostgreSQL
FROM postgres:15

# Establece las variables de entorno necesarias para PostgreSQL
ENV POSTGRES_USER=${DB_USER}
ENV POSTGRES_PASSWORD=${DB_PASSWORD}
ENV POSTGRES_DB=${DB_DATABASE}

# Copia el script SQL de inicialización en el directorio de inicialización de PostgreSQL
COPY db.sql /docker-entrypoint-initdb.d/

# Exponer el puerto 5432 para PostgreSQL
EXPOSE 5432